### ISSUE TITLE
Broken download link and extracted features

### ISSUE THREAD

**Issue by aleflabo** [TimSchoonbeek/IndustReal#2]
Hi! 

Thank you for sharing the code and the dataset, your work is really interesting.

The download link seems to be broken, can you point me to the current one? 
Are there also already extracted features of the frames that can be used?

Thank you in advance.

Alessandro

**Comment by TimSchoonbeek** [comment]
Hi Alessandro,

The download link is not yet available - the dataset is currently being uploaded to the hosting service and will soon become available. Once it is available, I will update the link and shoot a message here to update you.

We are uploading the trained model weights, but currently are not planning on uploading the extracted features as well. However, we do plan on uploading the ASD output for the best performing and synthetic-only trained models. 

Thanks for your interest in the dataset! 

Best,
Tim

**Comment by TimSchoonbeek** [comment]
Hi Alessandro,

The links are updated - the dataset is now publicly available!
