### ISSUE TITLE
Cam intrinsics data

### ISSUE THREAD

**Issue by lan-creator** [TimSchoonbeek/IndustReal#3]
Hello! Thank you for your great work! I wonder if I could find camera intrinsics of your PV cam. Thank you!

**Comment by TimSchoonbeek** [comment]
Hi! Thank you for your interest. I am sure I have them somewhere - I'll get back to you soon!

**Comment by TimSchoonbeek** [comment]
Here are the parameters. Apologies for the delay!

Camera matrix (mtx):
[[991.2671654    0.         621.15796503]
 [  0.         993.58792924 332.80244555]
 [  0.           0.           1.        ]]
 
 Distortion coefficients (dist):
 [[-4.84278831e-02  6.09241560e-01  1.20240805e-03  1.14830355e-04 -2.00550265e+00]]
